title: Munyong’s Blog
description: Kpop 가사 철학 읽기 · Apple Docs 번역 · 기타 등등
theme: minima
timezone: Asia/Seoul

# 상단 메뉴에 표시할 페이지
header_pages:
  - kpop.md
  - apple.md
  - etc.md

plugins:
  - jekyll-feed
